### ISSUE TITLE
RFC - Alert Component

### ISSUE THREAD

**Issue by navin-moorthy** [timelessco/renderlesskit-react-tailwind#15]
## The Goal:

Create an customizable, extendable & easily stylable Alert Component.

The Alert Component will follow [WAI-ARIA Alert](https://www.w3.org/TR/wai-aria-practices-1.2/#alert)

Key Resources for the Alert Component,

* https://chakra-ui.com/docs/feedback/alert
* https://ant.design/components/alert/
* https://material-ui.com/components/alert/

![image](https://user-images.githubusercontent.com/39694575/102593137-76161780-413a-11eb-9a5f-8b3f6fa1d185.png)

## Component Parts

* Alert: The wrapper for alert components.
![image](https://user-images.githubusercontent.com/39694575/102593499-f63c7d00-413a-11eb-9d3c-23a0a410ac08.png)
* AlertIcon: The visual icon for the alert that changes based on the status prop.
![image](https://user-images.githubusercontent.com/39694575/102593594-153b0f00-413b-11eb-8573-e9cd3129dace.png)
* AlertTitle: The title of the alert to be announced by screen readers.
![image](https://user-images.githubusercontent.com/39694575/102593634-1ff5a400-413b-11eb-935d-e3a960408ab3.png)
* AlertDescription: The description of the alert to be announced by screen readers.
![image](https://user-images.githubusercontent.com/39694575/102593906-811d7780-413b-11eb-9c6c-e0763349d7e3.png)
* AlertActionButton: The action butotn for the alert that changes based on the status prop.

## Usage
```js-jsx
<Alert status="success">
  <AlertIcon />
  <AlertTitle>Your browser is outdated!</AlertTitle>
  <AlertDescription>Your experience may be degraded.</AlertDescription>
  <AlertActionButton>Update</AlertActionButton>
  <Button aria-label="close"><ButtonIcon><CloseIcon/></ButtonIcon></Button>
</Alert>
```

### Alert
- status -  The status of the alert - "info" | "warning" | "success" | "error" | "offline

default: "info"

**Comment by navin-moorthy** [comment]
```js-jsx
<Button aria-label="close"><ButtonIcon><CloseIcon/></ButtonIcon></Button>
```

I think this is the reason Chakra has a dedicated Aria supported `IconButton`.
Material UI has also utilized `IconButton`.

What is your thought @anuraghazra ?

```js-jsx
<IconButton><CloseIcon/></IconButton>
```
This can be used in all the place where we need to use only the icon as children for the button.

But having a separate `CloseButton` seems to be more abstracted, but let me know your thought

**Comment by navin-moorthy** [comment]
@sandeepprabhakaran based on your feedback on Alert regarding the implementation of CloseButton like we do with Tag using `closable`.

I think we cannot do the same with Alert Component, since its a Compound Component.
I think it would be better to have it separate in this case instead of having it inside the prop 🤔 

What is your thought @anuraghazra ?

**Comment by anuraghazra** [comment]
I think we don't need a separate `closable` prop for alert because Alert can have multiple ActionButtons (eg: undo, redo buttons)

I Tag component we had closable prop because there can only be one single action button on tag.


IMO the current API is fine with the Compound approach.

**Comment by navin-moorthy** [comment]
> ```
> <Button aria-label="close"><ButtonIcon><CloseIcon/></ButtonIcon></Button>
> ```
> 
> I think this is the reason Chakra has a dedicated Aria supported `IconButton`.
> Material UI has also utilized `IconButton`.
> 
> What is your thought @anuraghazra ?
> 
> ```
> <IconButton><CloseIcon/></IconButton>
> ```
> 
> This can be used in all the place where we need to use only the icon as children for the button.
> 
> But having a separate `CloseButton` seems to be more abstracted, but let me know your thought

@sandeepprabhakaran says we could also have this, since `CloseButton` will be used in multiple places.

**Comment by navin-moorthy** [comment]
> I think we don't need a separate `closable` prop for alert because Alert can have multiple ActionButtons (eg: undo, redo buttons) & also note that the prop closable is very specific to the Tag usecase which only closes the Tag and in case of alert it can be closed, or even any other action can be added whatever user desires.
> 
> In Tag component we had closable prop because there can only be one single action button on tag.
> 
> IMO the current API is fine with the Compound approach.

Exactly my thought !
